
language: C

install:
 - sudo wget -q -P "/opt" "https://dl.dropboxusercontent.com/u/60324283/mono-3.2.3.tar.bz2"
 - sudo tar xkv -C "/opt" -f /opt/mono-3.2.3.tar.bz2
 - export PATH="/opt/bin:$PATH"
 - export LD_LIBRARY_PATH="/opt/bin"
 - mozroots --import --sync 
 - mono --version

script:
 - ./build.sh

